services:

  # Postgresql
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: postgres_password 
      POSTGRES_DB: taskdb
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  
  # Postgresql Admin
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin_password 
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:5050"
    networks:
      - postgres-network

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "6789:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../back/img:/usr/share/nginx/html/img
    restart: always

volumes:
  config:
  data:
  log:
  postgres:
  pgadmin:

networks:
  postgres-network:
    name: postgres-network